ALTER TABLE IF EXISTS welcome_config ADD COLUMN IF NOT EXISTS use_embed BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS welcome_config ADD COLUMN IF NOT EXISTS embed_color TEXT DEFAULT '#5865F2';
ALTER TABLE IF EXISTS welcome_config ADD COLUMN IF NOT EXISTS banner_url TEXT;
ALTER TABLE IF EXISTS welcome_config ADD COLUMN IF NOT EXISTS dm_message TEXT;
ALTER TABLE IF EXISTS welcome_config ADD COLUMN IF NOT EXISTS dm_enabled BOOLEAN DEFAULT false;
