ALTER TABLE IF EXISTS reminders ADD COLUMN IF NOT EXISTS recurring BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS reminders ADD COLUMN IF NOT EXISTS interval_ms BIGINT;
ALTER TABLE IF EXISTS reminders ADD COLUMN IF NOT EXISTS next_run TIMESTAMPTZ;
