ALTER TABLE IF EXISTS giveaways ADD COLUMN IF NOT EXISTS required_role_id TEXT;
ALTER TABLE IF EXISTS giveaways ADD COLUMN IF NOT EXISTS required_level INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS giveaways ADD COLUMN IF NOT EXISTS max_entries INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS giveaways ADD COLUMN IF NOT EXISTS winner_count INTEGER DEFAULT 1;
